# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tjaskula.github.io/Blog
gitlocation: https://github.com/tjaskula/Blog.git
gitbranch: gh-pages
title: Tomasz Jaskula's blog
description: >
    Software architecture, software craftsmanship, functional languages and mostly F#
	are topics dear to my heart. I don't restrict myself to talk only about these
	but will pick up topics that are of interest to me :)

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes